# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69df9a45a94ba7acf5592ab49822e7502331ffaf582cf33a85c0fda4ab166287e110a294f6ed2bae76c6992decc0cdea8338e100b7ee6ffe5a08b1b018838da4

test:
  secret_key_base: 91e52a3a18ab5e88f9a52473b38dc4758db681e01bf99a42989d2d82c2fed3f1777eb40241a22eb219bca1edb2ae265476fa0c1ee2d285e882519edb94a40517

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
